[flask]
SITE_URL = 'https://mysiteurl.com'
UPLOAD_FOLDER = '/tmp/erio-cabinet'
PERMANENT_UPLOAD_FOLDER = '/srv/erio-cabinet/uploads'
MAX_CONTENT_LENGTH = 268435456
SECRET_KEY = 'my long secret key'
SQLITE3_DATABASE = '/srv/erio-cabinet/erio.db'

[crypto]
suite = "itoko.crypto.suite.aes.AESSuite"

[persistence]


[shortener]
database_uri = "sqlite:///srv/itoko/erio.db"
