[flask]
SITE_URL = 'https://itoko.moe'
MAX_CONTENT_LENGTH = 268435456
SECRET_KEY = 'my long secret key'
SQLITE3_DATABASE = '/srv/erio-cabinet/erio.db'

[crypto]
suite = "itoko.crypto.suite.aesv2.AESV2Suite"

[storage]
temporary_folder = '/srv/erio-cabinet/uploads/temp'
permanent_folder = '/srv/erio-cabinet/uploads/perm'

[shortener]
database_uri = "sqlite:///srv/itoko/erio.db"
