# The default namespace is Flask
SITE_URL = 'https://itoko.moe'
MAX_CONTENT_LENGTH = 268435456
SECRET_KEY = 'my long secret key'
SQLITE3_DATABASE= "/srv/itoko/erio.db"

[ITOKO_STORAGE]
temporary_folder = '/srv/itoko/uploads/temp'
permanent_folder = '/srv/itoko/uploads/perm'
writer = "itoko.fs.format.v2:ItokoV2FormatFile"
readers = [
    "itoko.fs.format.v1:ItokoV1FormatReader",
    "itoko.fs.format.v2:ItokoV2FormatReader",
]
